// <auto-generated />
namespace Lms.IdentityModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Initmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initmig));
        
        string IMigrationMetadata.Id
        {
            get { return "201712081502193_Init mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
